---
title: "popularity_prediction"
author: "Daniel Redel"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(caret)
library(rpart)
library(rpart.plot)
library(rattle)
library(MLmetrics)
library(e1071)
library(neuralnet)
library(pROC)
library(vtable)

#rm(list=ls())

## Spotify Color Palette
spotycolor <- c("#33D66D", "#0DDEB4", "#7BE070", "#10C76B", "#4AC2AC")

```

## 0.  Data Import
```{r}

library(readr)
spotify_data <- read_csv("2 cleaning/spotify_data.csv") 

spotify_data <- spotify_data %>% 
  select(-duration_minutes, -n_songs, -avg_popularity)

```

## 1. Pre-Process Data
### Normalization
We only need to normalize those variables that don't take values between 0 and 1
```{r}

# Normalization Function
nor <- function(x) {
  (x-min(x))/(max(x)-min(x))
}


## Which ones needs normalization:
summary(spotify_data)
#year tempo duration | loudness
non_norm_var <- spotify_data[,c(3:5,9)]

## We Normalize
data2 <- as.data.frame(lapply(non_norm_var, nor))

## Combine Data
normaldata <- cbind(spotify_data[,1], data2, spotify_data[,-c(1, 3:5,9)])

##Base final:
data <- normaldata

```

### Data Partition
We split our data in a training sample and test sample:
```{r, include=FALSE}



## We will work with a sample, for computer size reasons
set.seed(456789)

r <- sample(nrow(data))
sample_df <- data[r,]
cut <- round(nrow(sample_df)*.25)
sample <- sample_df[1:cut,]
sample

## Train data and Test Data (70%-30%)
set.seed(123456)

r <- sample(nrow(sample))
shuffle_df <- sample[r,]

split <- round(nrow(shuffle_df)*.7)
train <- shuffle_df[1:split,]
test <-  shuffle_df[(split+1):nrow(shuffle_df),]

```

## 2. Machine Learning Models for Prediction

### Regression
```{r}

# Regression Prediction #
model_reg <- lm(popularity ~ ., data = train[,c(2:28)])

##Saving our Predictions
pred_train0 <- predict(model_reg, train)
pred_test0 <- predict(model_reg , newdata = test)

##############
##ASSESSMENT##
##############

## Calidad de ajuste en Train 
rmse_reg_train <- RMSE(pred_train0, train$popularity)
rae_reg_train <- RAE(pred_train0, train$popularity)
r2_reg_train <- R2_Score(pred_train0, train$popularity)
## Validacion del modelo con Test
rmse_reg_test <- RMSE(pred_test0, test$popularity)
rae_reg_test <- RAE(pred_test0, test$popularity)
r2_reg_test <- R2_Score(pred_test0, test$popularity)


```

### Decision Trees N°1: Simple Case
```{r, echo=FALSE}

# Regression Tree #
model_tree0 <- rpart(popularity ~ ., 
                    data = train[,c(2:28)], 
                    method = "anova")

## Summary & Plot
prp(model_tree0, box.palette = spotycolor) ## el modelo usa mucho la variable artist
plotcp(model_tree0)

##Variable Relative Importance
importance <- varImp(model_tree0) %>% 
  arrange(desc(Overall)) %>% 
  filter(Overall>0)
variables <- c("artist", "year", "speechiness", "acousticness", "duration", "instrumentalness", "loudness", "energy", "explicit")

importance %>%
  kbl(caption = "Variable Importance") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")

##Saving our Predictions
pred_train0 <- predict(model_tree0, train)
pred_test0 <- predict(model_tree0, test)

##############
##ASSESSMENT##
##############

## Calidad de ajuste en Train 
rmse_tree_train <- RMSE(pred_train0, train$popularity)
rae_tree_train <- RAE(pred_train0, train$popularity)
r2_tree_train <- R2_Score(pred_train0, train$popularity)
## Validacion del modelo con Test
rmse_tree_test <- RMSE(pred_test0, test$popularity)
rae_tree_test <- RAE(pred_test0, test$popularity)
r2_tree_test <- R2_Score(pred_test0, test$popularity)

```

### Decision Tree N°2: Prunning
```{r}

###################
## Loop Accuracy ##
###################

i=1                          
tree.optm=1                     
for (i in 1:15){ 
    tree.mod <-  rpart(popularity ~ ., 
                    data = train[,c(2:28)], 
                    method = "anova",
                    control = list(cp=0, maxdepth = i))
    pred <- predict(tree.mod, newdata = test)
    tree.optm[i] <- RMSE(pred, test$popularity)
    k=i  
    cat(k,'=', tree.optm[i],'\n')       
}

## Ploteamos
RMSE_plot <- plot(tree.optm, type="b", xlab="K-Value", ylab="RMSE level") #maxdepth = 7
RMSE_plot

ggsave('RMSE_plot.png', RMSE_plot, width = 8, height = 5.2)

#################
## FINAL MODEL ##
#################
model_tree1 <- rpart(popularity ~ ., 
                    data = train[,c(2:28)], 
                    method = "anova",
                    control = list(cp=0, maxdepth = 7))

## Summary & Plot
#prp(model_tree1, box.palette = spotycolor) ## el modelo usa mucho la variable artist


##Importancia de las Variables
importance <- varImp(model_tree1) %>% 
  arrange(desc(Overall)) %>% 
  filter(Overall>0.1)
variables <- c("artist", "year", "speechiness", "acousticness", "duration", "instrumentalness", "loudness", "energy", "explicit")

importance %>%
  kbl(caption = "Variable Importance") %>%
  kable_classic(full_width = F, html_font = "Cambria")

##Saving our Predictions
pred_train1 <- predict(model_tree1, train)
pred_test1 <- predict(model_tree1, newdata = test)

#############
##EVALUAMOS##
#############
## Calidad de ajuste en Train 
rmse_tree1_train <- RMSE(pred_train1, train$popularity)
rae_tree1_train <- RAE(pred_train1, train$popularity)
r2_tree1_train <- R2_Score(pred_train1, train$popularity)
## Validacion del modelo con Test
rmse_tree1_test <- RMSE(pred_test1, test$popularity)
rae_tree1_test <- RAE(pred_test1, test$popularity)
r2_tree1_test <- R2_Score(pred_test1, test$popularity)


```

## 3. Random Forest
```{r}

# Regression Tree #
model_tree0 <- rpart(popularity ~ ., 
                    data = train[,c(2:29)], 
                    method = "anova")

# Random Forest
library(randomForest)
#set.seed(2020)

model_rf <- train(popularity ~ ., 
                       data = train[,c(2:29)],
                       method = "rf",
                       trControl= trainControl(method = "cv", p=0.8),
                       na.action=na.omit,
                       cp = 0)
model_rf$finalModel ##ConfusionMatrix
plot(model_rf$finalModel)
varImp(model_rf)

##Guardamos las Predicciones
pred_rf <- predict(model_rf, train)
predval_rf <- predict(model_rf, newdata = test)


##############
##ASSESSMENT##
##############

## Calidad de ajuste en Train 
RMSE(pred_train0, train$popularity)
RAE(pred_train0, train$popularity)
R2_Score(pred_train0, train$popularity)
## Validacion del modelo con Test
RMSE(pred_test0, test$popularity)
RAE(pred_test0, test$popularity)
R2_Score(pred_test0, test$popularity)

```



## 4. Model Comparison
```{r, include=FALSE}

###############################
##ACCURACY COMPARISON ON TRAIN##
###############################

criterio <- c("RMSE", "RAE", "R2_Score")

regresion <- c(rmse_reg_train, rae_reg_train, r2_reg_train)
tree <- c(rmse_tree_train, rae_tree_train, r2_tree_train)
tree1 <- c(rmse_tree1_train, rae_tree1_train, r2_tree1_train)


comtable <- data.frame(criterio, regresion, tree, tree1) 
colnames(comtable) <- c("Criteria", "Linear Regression", "Decision Tree", "Decision Tree (pruned)")

comtable1 <- comtable %>% 
  kbl(caption = "Model Accuracy Comparison - Train") %>%
  kable_classic(full_width = F, html_font = "Cambria")
comtable1

##############################
##ACCURACY COMPARISON ON TEST##
##############################

regresion <- c(rmse_reg_test, rae_reg_test, r2_reg_test)
tree <- c(rmse_tree_test, rae_tree_test, r2_tree_test)
tree1 <- c(rmse_tree1_test, rae_tree1_test, r2_tree1_test)

comtable <- data.frame(criterio, regresion, tree, tree1) 
colnames(comtable) <- c("Criteria", "Linear Regression", "Decision Tree", "Decision Tree (pruned)")

comtable1 <- comtable %>% 
  kbl(caption = "Model Accuracy Comparison - Test") %>%
  kable_classic(full_width = F, html_font = "Cambria")
comtable1


```

## 5. Some Song Examples
```{r, include=FALSE}

cbind(test, as.data.frame(pred_test1)) %>% 
  filter(popularity<20, popularity>10) %>% 
  arrange(desc(popularity))


```








